### ISSUE TITLE
[GENERAL] Concurrency model concerns

### ISSUE THREAD

**Issue by smarzola** [immuni-app/immuni-backend-exposure-ingestion#15]
First of all, thank you for all the effort you put in this project, your care for sensitive topics has convinced even the paranoid people (like myself) to use the app. Kudos.

I’m a bit concerned about the concurrency model, you have chosen a really fast async framework (Sanic) running with the AsyncIO event loop but you are using incompatible network libraries, most notably MongoEngine, which is a mongoDB ODM on top of pymongo. [Pymongo does not support AsyncIO](https://api.mongodb.com/python/current/faq.html#does-pymongo-support-asynchronous-frameworks-like-gevent-asyncio-tornado-or-twisted)

Let’s take a look at this chunk of code https://github.com/immuni-app/immuni-backend-exposure-ingestion/blob/cbd2aca2079eb204558f0d8f179ec97676570365/immuni_exposure_ingestion/apis/ingestion.py#L133-L138
`upload_model.save()` is a blocking operation, you are not yielding control to another coroutine during the write operation, blocking the entire event loop - the most visible effect is that you can't serve other requests during the operation.
I would suggest to use an async mongoDB driver instead of pymongo (Motor) or to run the blocking code in a `concurrent.future.ThreadPoolExecutor` using [asyncio.loop.run_in_executor](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.run_in_executor)

Moreover, here https://github.com/immuni-app/immuni-backend-exposure-ingestion/blob/cbd2aca2079eb204558f0d8f179ec97676570365/immuni_exposure_ingestion/tasks/process_uploads.py#L35-L39 you are using Celery to schedule a periodic task, which instantiate an event loop purposely-built for an async function call. But it turns out that the function is not meant to be async at all:

* You are explicitly avoiding concurrency with a distributed lock https://github.com/immuni-app/immuni-backend-exposure-ingestion/blob/cbd2aca2079eb204558f0d8f179ec97676570365/immuni_exposure_ingestion/tasks/process_uploads.py#L56

* you are running blocking code https://github.com/immuni-app/immuni-backend-exposure-ingestion/blob/cbd2aca2079eb204558f0d8f179ec97676570365/immuni_exposure_ingestion/tasks/process_uploads.py#L78

Why bother with all the concurrency "inception" (Celery -> AsyncIO evt loop -> coroutine) then,  when what you want achieve is a serial execution? There is no need of concurrency here. What about a celery task that runs synchronous code?
One could also argue that even Celery is an overkill when the need is to launch a cron job, there are a bunch of tools that allows to keep control of task scheduling on the application layer, without all the celery machinery, [APScheduler](https://apscheduler.readthedocs.io/en/latest/) for instance.

Cheers

**Comment by earien** [comment]
hey there @smarzola , thanks so much for helping on this project, your analysis is great 😍 
I agree with you on the missed opportunity of actually leveraging coroutines in the APIs code, as well as having some overcomplicated code in the Celery tasks 👍 
We will review this part of the code and get back to you for further discussion in the next few days 😄

**Comment by xelhark** [comment]
Hi @smarzola !
Thanks a lot for your feedback, we’re glad you took the time to analyze the code in such detail!

Let’s get to your analysis:
About the blocking operations on Mongodb, you’re 100% right on your analysis. At the current state we don’t think it’s a major issue though, as those endpoints and those operations aren’t really performance critical:
- The process_uploads task is executed once or twice per day
- The upload endpoint might have some throughput but we don’t expect it to be very high (at most one call per infected user would get to that part)
- The exposure reporting service is served behind a CDN that will refresh its content ~hourly.

If you agree, I would post an “enhancement” issue to refactor the code in order to use something like motor for mongodb operations.

About the “inception” ( 😄 ) Celery -> AsyncIO evt loop -> coroutine, I also agree. The reason of that part of code is that the redis driver that we’re using is an async driver. For consistency reasons, we didn’t want to introduce a synchronous driver for that single redis call, so we ended up making that function asynchronous. Unfortunately, it isn’t supported by celery, thus leading to this workaround.

Do you have any suggestions on how to improve it?

**Comment by ocardia** [comment]
Hey @smarzola, we’re now going to close this issue as there are currently no actionable, and no further suggestion has been provided.

We'd like to thank you—again—for the time invested in analysing the code in such details. Hopefully, when Celery 5.0 will be released, there will be support for what you proposed.

For now, we are going to close this issue.
